ALTER TABLE tasks ADD COLUMN description TEXT;
ALTER TABLE tasks ADD COLUMN assignee_id UUID NOT NULL REFERENCES users(id);
ALTER TABLE tasks ADD COLUMN status VARCHAR(10) NOT NULL DEFAULT 'open';
ALTER TABLE tasks ADD COLUMN completed_at TIMESTAMP;
